stages:
  - deploy

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - echo "Начинаем локальный деплой на *** в папку auto-attributs-cmdbmp..."
    
    # 1. Синхронизируем файлы от имени пользователя проекта (использует NOPASSWD правило в sudoers)
    - sudo -u *** rsync -rlDvz --delete --no-owner --no-group --chmod=D755,F644 --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='venv/' --exclude='logs/' --exclude='files/' --exclude='.env' --exclude='__pycache__/' ./ /opt/auto-attributs-cmdbmp/

    # 2. Переходим в папку
    - cd /opt/auto-attributs-cmdbmp/
    
    # 3. Обновляем зависимости. sudo здесь НЕ НУЖЕН, файлы уже принадлежат isd-automation!
    - ./venv/bin/python3 -m pip install --upgrade pip
    - ./venv/bin/pip install -r requirements.txt
    
    - echo "Деплой успешно завершен!"
